language: python
python:
  - "3.7"

services:
  - docker

before_script:
  - pip install docker-compose
  - docker-compose run app sh -c "python manage.py makemigrations"
  - docker-compose run app sh -c "python manage.py migrate"

script:
  - docker-compose run app sh -c "python manage.py test && flake8"
