language: python
python:
  - "3.7"

services:
  - docker

before_script: pip install docker-compose

script:
  - docker-compose run app python manage.py makemigrations
  - docker-compose run app python manage.py migrate
  - docker-compose run app python manage.py test
  - docker-compose run app python manage.py flake8
