language: python
python:
  - "3.7"

services:
  - docker

before_script: pip install docker-compose

script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test
  - python manage.py flake8
