# Generated by Django 3.0.3 on 2020-03-02 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('FOOD', 'food'), ('BILLS', 'bills'), ('CAR', 'car'), ('TRANSPORT', 'transport'), ('INCOME', 'income'), ('TRANSFER', 'transfer')], max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('EXPENSE', 'expense'), ('INCOME', 'income')], max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ImageField(blank=True, upload_to='invoices/')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='transactions.Wallet')),
            ],
        ),
    ]
