# Generated by Django 3.0.2 on 2020-01-30 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20200128_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('FOOD', 'food'), ('BILLS', 'bills'), ('CAR', 'car'), ('TRANSPORT', 'transport'), ('INCOME', 'income'), ('TRANSFER', 'transfer')], max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('EXPENSE', 'expense'), ('INCOME', 'income')], max_length=50),
        ),
    ]
