# Generated by Django 3.0.3 on 2020-03-04 13:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20200304_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
