# Generated by Django 3.0.3 on 2020-03-05 08:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20200304_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='created',
            field=models.DateField(default=datetime.datetime(2020, 3, 5, 8, 23, 26, 51550, tzinfo=utc)),
        ),
    ]
