# Generated by Django 3.0.3 on 2020-03-05 08:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20200305_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='created',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
